from turtle import *
import time
import random
setup(500,500)
r=random.randint(0,255)
g=random.randint(0,255)
b=random.randint(0,255)
colormode(255)
shape("circle")
bgcolor(r,g,b)
def drawround(size,fill):
    pendown()
    if fill:
        begin_fill()
    setheading(180)
    circle(size,360)
    if fill:
        end_fill()
def drawhead():
    color("blue")
    penup()
    goto(0,100)
    drawround(75,True)
    color("white")
    penup()
    goto(0,72)
    drawround(60,True)
def draweyes():
    color("black","white")
    penup()
    goto(-15,80)
    drawround(17,True)
    penup()
    goto(19,80)
    drawround(17,True)
    color("black")
    penup()
    goto(-8,70)
    drawround(6,True)
    penup()
    goto(12,70)
    drawround(6,True)
def drawnose():
    color("red")
    penup()
    goto(0,40)
    drawround(7,True)
def drawmouth():
    color("black")
    penup()
    goto(-30,-20)
    pendown()
    setheading(-27)
    circle(70,55)
    penup()
    goto(0,26)
    pendown()
    goto(0,-25)    
drawhead()
draweyes()
drawnose()
drawmouth()  
time.sleep(5)